name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - main
jobs:
  analyze:
    runs-on: ubuntu-latest
    name: "Analyze"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.1"
      - run: flutter pub get
      - run: flutter analyze
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /WidGen/
